//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Typing.DataAccess.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Typing.DataAccess.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is an ancient Mariner,
        ///And he stoppeth one of three.
        ///`By thy long grey beard and glittering eye,
        ///Now wherefore stopp&apos;st thou me?
        ///
        ///The bridegroom&apos;s doors are opened wide,
        ///And I am next of kin;
        ///The guests are met, the feast is set:
        ///Mayst hear the merry din.&apos;
        ///
        ///He holds him with his skinny hand,
        ///&quot;There was a ship,&quot; quoth he.
        ///`Hold off! unhand me, grey-beard loon!&apos;
        ///Eftsoons his hand dropped he.
        ///
        ///He holds him with his glittering eye - 
        ///The Wedding-Guest stood still,
        ///And listens like a three ye [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AncientMariner {
            get {
                return ResourceManager.GetString("AncientMariner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provider cannot be null.
        /// </summary>
        internal static string AsyncTextWorker_AsyncTextWorker_provider_cannot_be_null {
            get {
                return ResourceManager.GetString("AsyncTextWorker_AsyncTextWorker_provider_cannot_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every afternoon, as they were coming from school, the children used to go and play in the Giant&apos;s garden.
        ///
        ///It was a large lovely garden, with soft green grass. Here and there over the grass stood beautiful flowers like stars, and there were twelve peach-trees that in the spring-time broke out into delicate blossoms of pink and pearl, and in the autumn bore rich fruit. The birds sat on the trees and sang so sweetly that the children used to stop their games in order to listen to them. &quot;How happy we are her [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelfishGiant {
            get {
                return ResourceManager.GetString("SelfishGiant", resourceCulture);
            }
        }
    }
}
